#!/usr/bin/env bash

STEP="$1"

BACKEND_DIR="./backend"

update_backend_version() {
    local valid_steps=("major" "minor" "patch")

    if [[ ! ${valid_steps[@]} =~ $STEP ]]; then
        echo "Expected either \"major\", \"minor\" or \"patch\" as argument"
        exit 1
    fi

    echo "Updating backend version"
    pushd "$BACKEND_DIR" &> /dev/null
        npm version "$STEP"
    popd &> /dev/null
}

update_backend_version

VERSION=v$(jq -r .version "$BACKEND_DIR/package.json")

echo "Updating version in install"
sed -i 's|^VERSION=".*"$|VERSION="'"$VERSION"'"|' "./install"

echo "Updating version in update"
sed -i 's|^VERSION=".*"$|VERSION="'"$VERSION"'"|' "./update"
